version: '3.5'

services:

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 443:443
    env_file:
      - .env
    restart: always
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html/
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    image: wordpress
    env_file:
      - .env
    restart: always
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html/
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    image: mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file:
      - .env

networks:
  inception:
    name: inception

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: '/home/ntozzi.42.fr/data/wordpress/'
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: '/home/ntozzi.42.fr/data/db/'
